// <auto-generated />
using System;
using MASA.RetailPOS.App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MASA.RetailPOS.App.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("MASA.RetailPOS.App.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconSource")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 7, 3, 48, 3, 181, DateTimeKind.Local).AddTicks(6364),
                            Name = "مشروبات",
                            UpdatedAt = new DateTime(2026, 6, 7, 3, 48, 3, 181, DateTimeKind.Local).AddTicks(6366)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 7, 3, 48, 3, 181, DateTimeKind.Local).AddTicks(6368),
                            Name = "حلويات",
                            UpdatedAt = new DateTime(2026, 6, 7, 3, 48, 3, 181, DateTimeKind.Local).AddTicks(6369)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 7, 3, 48, 3, 181, DateTimeKind.Local).AddTicks(6371),
                            Name = "أطعمة",
                            UpdatedAt = new DateTime(2026, 6, 7, 3, 48, 3, 181, DateTimeKind.Local).AddTicks(6371)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 7, 3, 48, 3, 181, DateTimeKind.Local).AddTicks(6372),
                            Name = "منتجات متنوعة",
                            UpdatedAt = new DateTime(2026, 6, 7, 3, 48, 3, 181, DateTimeKind.Local).AddTicks(6373)
                        });
                });

            modelBuilder.Entity("MASA.RetailPOS.App.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalDebt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("MASA.RetailPOS.App.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Discount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxTotal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("UserId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("MASA.RetailPOS.App.Models.InvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ProductId");

                    b.ToTable("InvoiceItems");
                });

            modelBuilder.Entity("MASA.RetailPOS.App.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageSource")
                        .HasColumnType("TEXT");

                    b.Property<int>("MinimumStockAlert")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "1001",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 7, 3, 48, 3, 181, DateTimeKind.Local).AddTicks(6407),
                            MinimumStockAlert = 0,
                            Name = "قهوة تركية",
                            PurchasePrice = 0m,
                            SalePrice = 25.00m,
                            StockQuantity = 100,
                            TaxRate = 0m,
                            UnitOfMeasure = "Piece",
                            UpdatedAt = new DateTime(2026, 6, 7, 3, 48, 3, 181, DateTimeKind.Local).AddTicks(6408)
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "1002",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 7, 3, 48, 3, 181, DateTimeKind.Local).AddTicks(6412),
                            MinimumStockAlert = 0,
                            Name = "شاي أخضر",
                            PurchasePrice = 0m,
                            SalePrice = 15.00m,
                            StockQuantity = 100,
                            TaxRate = 0m,
                            UnitOfMeasure = "Piece",
                            UpdatedAt = new DateTime(2026, 6, 7, 3, 48, 3, 181, DateTimeKind.Local).AddTicks(6413)
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "1003",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 7, 3, 48, 3, 181, DateTimeKind.Local).AddTicks(6415),
                            MinimumStockAlert = 0,
                            Name = "عصير برتقال",
                            PurchasePrice = 0m,
                            SalePrice = 20.00m,
                            StockQuantity = 100,
                            TaxRate = 0m,
                            UnitOfMeasure = "Piece",
                            UpdatedAt = new DateTime(2026, 6, 7, 3, 48, 3, 181, DateTimeKind.Local).AddTicks(6415)
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "1004",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 7, 3, 48, 3, 181, DateTimeKind.Local).AddTicks(6417),
                            MinimumStockAlert = 0,
                            Name = "مياه معدنية",
                            PurchasePrice = 0m,
                            SalePrice = 5.00m,
                            StockQuantity = 100,
                            TaxRate = 0m,
                            UnitOfMeasure = "Piece",
                            UpdatedAt = new DateTime(2026, 6, 7, 3, 48, 3, 181, DateTimeKind.Local).AddTicks(6417)
                        },
                        new
                        {
                            Id = 5,
                            Barcode = "1005",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 7, 3, 48, 3, 181, DateTimeKind.Local).AddTicks(6419),
                            MinimumStockAlert = 0,
                            Name = "مشروب غازي",
                            PurchasePrice = 0m,
                            SalePrice = 7.00m,
                            StockQuantity = 100,
                            TaxRate = 0m,
                            UnitOfMeasure = "Piece",
                            UpdatedAt = new DateTime(2026, 6, 7, 3, 48, 3, 181, DateTimeKind.Local).AddTicks(6419)
                        },
                        new
                        {
                            Id = 6,
                            Barcode = "1006",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 7, 3, 48, 3, 181, DateTimeKind.Local).AddTicks(6421),
                            MinimumStockAlert = 0,
                            Name = "كابتشينو",
                            PurchasePrice = 0m,
                            SalePrice = 30.00m,
                            StockQuantity = 100,
                            TaxRate = 0m,
                            UnitOfMeasure = "Piece",
                            UpdatedAt = new DateTime(2026, 6, 7, 3, 48, 3, 181, DateTimeKind.Local).AddTicks(6422)
                        },
                        new
                        {
                            Id = 7,
                            Barcode = "1007",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 6, 7, 3, 48, 3, 181, DateTimeKind.Local).AddTicks(6423),
                            MinimumStockAlert = 0,
                            Name = "كيك شوكولاتة",
                            PurchasePrice = 0m,
                            SalePrice = 45.00m,
                            StockQuantity = 100,
                            TaxRate = 0m,
                            UnitOfMeasure = "Piece",
                            UpdatedAt = new DateTime(2026, 6, 7, 3, 48, 3, 181, DateTimeKind.Local).AddTicks(6424)
                        },
                        new
                        {
                            Id = 8,
                            Barcode = "1008",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 6, 7, 3, 48, 3, 181, DateTimeKind.Local).AddTicks(6426),
                            MinimumStockAlert = 0,
                            Name = "كرواسون",
                            PurchasePrice = 0m,
                            SalePrice = 18.00m,
                            StockQuantity = 100,
                            TaxRate = 0m,
                            UnitOfMeasure = "Piece",
                            UpdatedAt = new DateTime(2026, 6, 7, 3, 48, 3, 181, DateTimeKind.Local).AddTicks(6426)
                        },
                        new
                        {
                            Id = 9,
                            Barcode = "1009",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 6, 7, 3, 48, 3, 181, DateTimeKind.Local).AddTicks(6464),
                            MinimumStockAlert = 0,
                            Name = "ساندويتش الدجاج",
                            PurchasePrice = 0m,
                            SalePrice = 35.00m,
                            StockQuantity = 100,
                            TaxRate = 0m,
                            UnitOfMeasure = "Piece",
                            UpdatedAt = new DateTime(2026, 6, 7, 3, 48, 3, 181, DateTimeKind.Local).AddTicks(6465)
                        },
                        new
                        {
                            Id = 10,
                            Barcode = "1010",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 6, 7, 3, 48, 3, 181, DateTimeKind.Local).AddTicks(6467),
                            MinimumStockAlert = 0,
                            Name = "بيتزا خضار",
                            PurchasePrice = 0m,
                            SalePrice = 40.00m,
                            StockQuantity = 100,
                            TaxRate = 0m,
                            UnitOfMeasure = "Piece",
                            UpdatedAt = new DateTime(2026, 6, 7, 3, 48, 3, 181, DateTimeKind.Local).AddTicks(6467)
                        },
                        new
                        {
                            Id = 11,
                            Barcode = "1011",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 6, 7, 3, 48, 3, 181, DateTimeKind.Local).AddTicks(6469),
                            MinimumStockAlert = 0,
                            Name = "بطاطس مقلية",
                            PurchasePrice = 0m,
                            SalePrice = 15.00m,
                            StockQuantity = 100,
                            TaxRate = 0m,
                            UnitOfMeasure = "Piece",
                            UpdatedAt = new DateTime(2026, 6, 7, 3, 48, 3, 181, DateTimeKind.Local).AddTicks(6469)
                        },
                        new
                        {
                            Id = 12,
                            Barcode = "1012",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 6, 7, 3, 48, 3, 181, DateTimeKind.Local).AddTicks(6471),
                            MinimumStockAlert = 0,
                            Name = "آيس كريم",
                            PurchasePrice = 0m,
                            SalePrice = 25.00m,
                            StockQuantity = 100,
                            TaxRate = 0m,
                            UnitOfMeasure = "Piece",
                            UpdatedAt = new DateTime(2026, 6, 7, 3, 48, 3, 181, DateTimeKind.Local).AddTicks(6471)
                        });
                });

            modelBuilder.Entity("MASA.RetailPOS.App.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalDebt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("MASA.RetailPOS.App.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 7, 3, 48, 3, 181, DateTimeKind.Local).AddTicks(5078),
                            FullName = "Administrator",
                            PasswordHash = "240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9",
                            Role = "Admin",
                            UpdatedAt = new DateTime(2026, 6, 7, 3, 48, 3, 181, DateTimeKind.Local).AddTicks(5089),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("MASA.RetailPOS.App.Models.Invoice", b =>
                {
                    b.HasOne("MASA.RetailPOS.App.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("MASA.RetailPOS.App.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MASA.RetailPOS.App.Models.InvoiceItem", b =>
                {
                    b.HasOne("MASA.RetailPOS.App.Models.Invoice", "Invoice")
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MASA.RetailPOS.App.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MASA.RetailPOS.App.Models.Product", b =>
                {
                    b.HasOne("MASA.RetailPOS.App.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MASA.RetailPOS.App.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MASA.RetailPOS.App.Models.Invoice", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
